INSERT INTO COMPANY_DATA (COMPANY, WASTEWATER_COST, WATER_COST) VALUES ('THAMES_WATER', '0.8963', '1.3818');
INSERT INTO COMPANY_DATA (COMPANY, WASTEWATER_COST, WATER_COST) VALUES ('SOUTHERN_WATER', '2.045', '1.487');
INSERT INTO COMPANY_DATA (COMPANY, WASTEWATER_COST, WATER_COST) VALUES ('AFFINITY_WATER', '0.8963', '1.7266');

INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Washing machine', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Dishwasher', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Handwashing dishes', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Kettle', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Handwashing food - bowl', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Handwashing food - tap', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Bath - full', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Bath - not full', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Tap running - teeth', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Tap running - shaving', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Shower', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Toilet', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Garden hose', 1);
INSERT INTO WATER_CONSUMER (APPLIANCE, CONSUMPTION) VALUES ('Car wash', 1);